# Configuration file for SafeItemFrames
# https://www.spigotmc.org/resources/safeitemframes.17351/
# Created by KevinNovak

# ============================================
# Metrics
# ============================================
# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/SafeItemFrames/
# default: metrics: true
metrics: true
